### PR TITLE
Fixing some edge cases for initializers

### LINKED ISSUE #335: ObjectInitializer in CollectionInitializer breaking
```
namespace NS
{
    class ClassName
    {
        void MethodName()
        {
            List<EmailVariable> parameters = new()
                {
                    new EmailVariable()
                    {
                        Parameter = "Customer",
                        IsValidFinalParameter = false,
                        FollowUpVariables = new List<EmailVariable>()
                        {
                            new()
                            { Parameter = "Name" }
                        }
                    }
                };
        }
    }
}
// used to be
namespace NS
{
    class ClassName
    {
        void MethodName()
        {
            List<EmailVariable> parameters = new()
                {
                    new EmailVariable()
                    {
                        Parameter = "Customer",
                        IsValidFinalParameter = false,
                        FollowUpVariables = new List<EmailVariable>()
                        {
                            new() { Parameter = "Name" }
                        }
                    }
                };
        }
    }
}

### LINKED ISSUE #336: ObjectInitializer keeping brace on same line
```c#
class ClassName
{
    void MethodName()
    {
        using var process = new Process()
        {
            StartInfo = {
                FileName = filename,
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            }
        };
    }
}
// should be
class ClassName
{
    void MethodName()
    {
        using var process = new Process()
        {
            StartInfo =
            {
                FileName = filename,
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            }
        };
    }
}

### PR DESCRIPTION
**Pull request by belav**
closes #335
closes #336

### CODE REVIEW

**Review by shocklateboy92 — APPROVED** [review]
Woah... it's been a while!
LGTM.

File: Src/CSharpier/SyntaxPrinter/RightHandSide.cs [hunk 1]
```diff
@@ -12,23 +13,21 @@ public static Doc Print(ExpressionSyntax node)
...
             {
+                InitializerExpressionSyntax initializerExpressionSyntax => InitializerExpression.PrintWithLine(
+                    initializerExpressionSyntax
+                ),
                 InvocationExpressionSyntax
                 or ParenthesizedLambdaExpressionSyntax
                 or ObjectCreationExpressionSyntax
                 or ElementAccessExpressionSyntax
                 or ArrayCreationExpressionSyntax
+                or InitializerExpressionSyntax
```
Comment (respel) [inline Src/CSharpier/SyntaxPrinter/RightHandSide.cs:24]: This might be redundant since you're including it above anyway.

File: Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs [hunk 2]
```diff
@@ -21,10 +21,20 @@ string groupId
             return Print(node, groupId);
         }
 
-        private static Doc Print(InitializerExpressionSyntax node, string? groupId)
+        public static Doc PrintWithLine(InitializerExpressionSyntax node)
```
Comment (respel) [inline Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs:24]: **suggestion**: I think stuff like `PrintWithLine` and `PrintWithConditionalSpace` might be better placed inlined at the call site rather than have special functions for one-off use cases.

**Comment by belav** [comment]
> Woah... it's been a while!

Don't worry, I was just on a long vacation. I'll fill up your inbox with new PRs soon!

File: Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs (hunk 2 above)
Comment (belav) [reply Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs]: I was able to move the logic for `PrintWithLine` into `InitializerExpression` itself.
And because `PrintWithConditionalSpace` ended up not using the `Doc.Group`, the logic for that could be inlined in `ObjectCreationExpression`.
Much nicer this way!

Comment (respel) [reply Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/InitializerExpression.cs]: image
