### PR TITLE
Fixing some constructor edge cases

### LINKED ISSUE #298: Constructor with Base edge cases
These are a couple of edge cases for the constructors with bases
```c#
        public ChangePassword(
            HttpClient client,
            IHtmlDocument changePassword,
            DefaultUIContext context
        ) : base(client, changePassword, context) {
            _changePasswordForm = HtmlAssert.HasForm("#change-password-form", changePassword);
        }
// should probably be
        public ChangePassword(
            HttpClient client,
            IHtmlDocument changePassword,
            DefaultUIContext context
        ) : base(client, changePassword, context)
        {
            _changePasswordForm = HtmlAssert.HasForm("#change-password-form", changePassword);
        }
// but I think no body should be
        public ChangePassword(
            HttpClient client,
            IHtmlDocument changePassword,
            DefaultUIContext context
        ) : base(client, changePassword, context) { }
```
I'm not sure why this one is different than the existing test case
```c#
    protected ColorSpan(RgbColor rgbColor, AnsiControlCode ansiControlCode)
        : base(
        GetName(rgbColor) ?? throw new ArgumentNullException(nameof(rgbColor)),
        ansiControlCode
    )
    {
        RgbColor = rgbColor;
    }
// Should probably be this
    protected ColorSpan(RgbColor rgbColor, AnsiControlCode ansiControlCode)
        : base(
            GetName(rgbColor) ?? throw new ArgumentNullException(nameof(rgbColor)),
            ansiControlCode
        )
    {
        RgbColor = rgbColor;
    }
```
This is the existing test case when it has a body
```c#
    public ReallyLoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogMethodName()
        : base(
            reallyLooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongParameterIMeanIt
        )
    {
        var x = 1;
    }
```

### PR DESCRIPTION
**Pull request by belav**
closes #298

### CODE REVIEW

File: Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs [hunk 1]
```diff
@@ -173,18 +199,31 @@ public static Doc Print(CSharpSyntaxNode node)
             if (constraintClauses != null)
             {
                 docs.Add(
-                    groupId != null
-                        ? ConstraintClauses.PrintWithConditionalSpace(constraintClauses, groupId)
+                    parameterGroupId != null
+                        ? ConstraintClauses.PrintWithConditionalSpace(
+                                constraintClauses,
+                                parameterGroupId
+                            )
```
Comment (shocklateboy92) [inline Src/CSharpier/SyntaxPrinter/SyntaxNodePrinters/BaseMethodDeclaration.cs:206]: Do you think we should half-indent ternary operators?
That way, the closing parenthesis will be aligned with the start of the method.

And things that aren't method calls (e.g. binary operators) usually indent themselves anyway, so they should look fine.
